### ISSUE TITLE
[功能建议] 添加配置项可以不生成 index.html 以及起服务

### ISSUE THREAD

**Issue by hipi** [voderl/font-slice#2]
可以添加配置项，允许只静默生成文件，而不生成 `index.html` 文件以及不创建静态服务。

**Comment by voderl** [comment]
好的，可以在 options 里加上 slient， 为 true 的话不生成  index.html 及启动服务器，这个我稍后处理下。

> ps. 问下这个需求是出于什么考虑，要在服务器上跑脚本吗？

**Comment by hipi** [comment]
> 好的，可以在 options 里加上 slient， 为 true 的话不生成 index.html 及启动服务器，这个我稍后处理下。
> 
> > ps. 问下这个需求是出于什么考虑，要在服务器上跑脚本吗？

写了脚本一次有多个字体切割，但是起了服务 不会结束进程 导致一直走不下去。

**Comment by hipi** [comment]
此外我觉得可以 再加一个 `formatsFileName` 选项，可以配置生成的分割文件名

**Comment by voderl** [comment]
好的，计划添加以下 options，可以看下能否满足你的需求。预计今晚处理完成
```js
{
   preview: true, // 默认为 true，为 false 时不生成 index.html 及启动服务器
   generateFontSubsetName: (fontFamily, index) => `${fontFamily}.${index + 1}` // 默认为该函数
}
```

**Comment by hipi** [comment]
> 好的，计划添加以下 options，可以看下能否满足你的需求。预计今晚处理完成
> 
> ```js
> {
>    preview: true, // 默认为 true，为 false 时不生成 index.html 及启动服务器
>    generateFontSubsetName: (fontFamily, index) => `${fontFamily}.${index + 1}` // 默认为该函数
> }
> ```

非常 Nice :laughing:  , 预想 `generateFontSubsetName` 就是个函数的

**Comment by voderl** [comment]
已经更新版本 1.0.2，辛苦试用下是否符合预期
