### ISSUE TITLE
切出来的切片，有些用不了

### ISSUE THREAD

**Issue by sijunzi** [voderl/font-slice#5]
大佬，我又来了。

![image](https://github.com/voderl/font-slice/assets/16330789/97693827-3118-4998-8b65-c771795d9520)
很神奇，有些切片浏览器会报错

![image](https://github.com/voderl/font-slice/assets/16330789/9715ee6a-f9db-464d-8ade-2e00337645cb)

有些又不会，同样的是思源的字体，哈哈

**Comment by voderl** [comment]
你看下请求的链接，有对应的文件吗？再看下本地生成字体的目录有对应的文件吗？会不会是对应的文件没有上传上去？

**Comment by sijunzi** [comment]
文件上传上去了，没找到文件会404，这是503









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "voderl/font-slice"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月26日(星期一) 晚上6:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [voderl/font-slice] 切出来的切片，有些用不了 (Issue #5)





 
你看下请求的链接，有对应的文件吗？再看下本地生成字体的目录有对应的文件吗？会不会是对应的文件没有上传上去？

**Comment by voderl** [comment]
没有遇到过，感觉像是服务器的问题，会不会是并发一下子太多了超过了服务器限制？

**Comment by sijunzi** [comment]
谢谢大佬，忘记了，我给限制了一个IP最多30个并发，好像是超并发了
