### ISSUE TITLE
部分字符显示错误/无法加载

### ISSUE THREAD

**Issue by yuyayang02** [voderl/font-slice#7]
我在使用切片工具将Fira Code字体切片使用后，发现一些字符没有按期望的效果显示

具体使用样式是：
font-family: Fira Code, LXGW, sans-serif;

具体情况是：
- \t字符被框选后出现未知字符的样式
<img width="354" alt="image" src="https://github.com/voderl/font-slice/assets/98627866/25ea4969-1c7d-47f1-a7af-c045bffa62d9">
- 空格字符变的非常窄，并且将`font-family: Fira Code, LXGW, sans-serif;`修改为`font-family: Fira Code,monospace,LXGW,sans-serif;`后，空格宽度出现明显变化。经排查包含空格的第29号字体文件已被加载，但不知为何空格未能正常显示

以上两种情况都在使用完整未切片的字体文件后消失

或者是我使用方法不正确？

**Comment by voderl** [comment]
哈喽，抱歉现在才回复，可以发下使用的切片字体文件吗？或者可以试下一个类似的字体切片项目：https://github.com/KonghaYao/cn-font-split
